// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFUMeqR4LwOFcRk95qBCmKmZdQSxiKTzI',
    appId: '1:417317117395:web:e9a954e788857892366326',
    messagingSenderId: '417317117395',
    projectId: 'email-app-final25',
    authDomain: 'email-app-final25.firebaseapp.com',
    storageBucket: 'email-app-final25.firebasestorage.app',
    measurementId: 'G-B0LFWWNVFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_dmPWrOA-W4dQmL4JG85QJJomQ4XrBc8',
    appId: '1:417317117395:android:3602fb928374d100366326',
    messagingSenderId: '417317117395',
    projectId: 'email-app-final25',
    storageBucket: 'email-app-final25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFIfGzkrJdcOUQ394tF5xaAc61f7grldY',
    appId: '1:417317117395:ios:09d421502e64fd62366326',
    messagingSenderId: '417317117395',
    projectId: 'email-app-final25',
    storageBucket: 'email-app-final25.firebasestorage.app',
    iosBundleId: 'com.example.emailApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFIfGzkrJdcOUQ394tF5xaAc61f7grldY',
    appId: '1:417317117395:ios:09d421502e64fd62366326',
    messagingSenderId: '417317117395',
    projectId: 'email-app-final25',
    storageBucket: 'email-app-final25.firebasestorage.app',
    iosBundleId: 'com.example.emailApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFUMeqR4LwOFcRk95qBCmKmZdQSxiKTzI',
    appId: '1:417317117395:web:3491b78eea236911366326',
    messagingSenderId: '417317117395',
    projectId: 'email-app-final25',
    authDomain: 'email-app-final25.firebaseapp.com',
    storageBucket: 'email-app-final25.firebasestorage.app',
    measurementId: 'G-8WH8NXKNX9',
  );
}
